name = "alansa-control-agricola"
compatibility_date = "2026-09-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "alansa-agricola-db"
database_id = "8f16df50-c126-4704-9bda-4cc635be7699"
